---
# Get the tarball of OMERO.server that matches {{ omero_version }}

- name: download and unpackage the omero tarball
  unarchive:
    src: "http://downloads.openmicroscopy.org/omero/{{ omero_version }}/artifacts/OMERO.server-{{ omero_version }}-{{ ice_version }}-{{ omero_branch }}.zip"
    remote_src: yes
    dest: "{{ omero_home }}"
    owner: "{{ omero_user_name }}"
    group: "{{ omero_user_name }}"
    creates: "{{ omero_home }}/OMERO.server-{{ omero_version }}-{{ ice_version }}-{{ omero_branch }}/LICENSE.txt"

- name: make a symbolic link to the omero server directory
  become: yes
  become_user: "{{ omero_user_name }}"
  file:
    src: "{{ omero_home }}/OMERO.server-{{ omero_version }}-{{ ice_version }}-{{ omero_branch }}"
    dest: "{{ omero_home }}/{{ omero_server_link }}"
    state: link

- name: install OMERO prerequisite software
  become: yes
  become_user: root
  pip: requirements="{{ omero_home }}/{{ omero_server_link }}/share/web/requirements-py27.txt"

# Configure the web server

- name: configure the omero web application server
  become: yes
  become_user: "{{ omero_user_name }}"
  command: "{{ omero_cmd }} config set omero.web.application_server wsgi-tcp"

- name: create symlinks for static media files
  become: yes
  become_user: "{{ omero_user_name }}"
  command: "{{ omero_cmd }} web syncmedia"

# Install Django.

- name: install django
  pip: requirements={{ omero_home }}/{{ omero_server_link }}/share/web/requirements-py27-nginx.txt

# Switch off httpd

- name: check if Apache is present
  stat: path=/etc/init.d/httpd
  register: service_status

- name: disable Apache httpd
  become: yes
  service:
    name: httpd
    enabled: no
  when: service_status.stat.exists
