---

- name: create the omero backup directory
  file: path={{ omero_backup_dir }}
        owner="{{ omero_admin_user }}"
        state=directory

- name: add cron job to backup postgres db
  cron: name="Backup OMERO postgres DB"
        minute="1"
        hour="4"
        weekday="*"
        month="*"
        job="su -c '/bin/pg_dump omero > {{ omero_backup_dir}}/$(/bin/date +\%Y-\%m-\%d-\%H-\%M).sql && /bin/chown omero {{ omero_backup_dir}}/$(/bin/date +\%Y-\%m-\%d-\%H-\%M).sql' -s /bin/sh postgres"
