---
# Install and configure ferm.
#

- name: install iptables-services for centos7  # needed save iptables handler
  yum: name=iptables-services
       state=present
  ignore_errors: yes   # in case we run on centos6

- name: install ferm
  yum: name=ferm
       state=present

- name: add /etc/ferm directory
  file: path=/etc/ferm
        mode=0700
        state=directory

- name: add the ferm.conf file to /etc/ferm
  copy: src=ferm.conf
        dest=/etc/ferm/ferm.conf
  notify: run ferm
