---
# Install and configure apache.

- name: install Apache and mod_wsgi
  yum: name={{ item }}
       state=present
  with_items:
    - httpd
    - mod_wsgi

- name: start apache and enable at boot
  service: name=httpd
           enabled=yes
           state=started

- name: open up http, https
  lineinfile: dest=/etc/ferm/ferm.conf
              line='proto tcp dport (http https) ACCEPT;'
              insertafter='# Ansible specified rules.'
  notify: run ferm

