---

# Install and configure postgres.

- name: add the postgres repo
  yum:
    name: https://yum.postgresql.org/11/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  ignore_unreachable: true
  ignore_errors: true

- name: install postgres
  yum:
    name: [ postgresql11, postgresql11-server ]
    state: present

- name: install ansible dependencies for interacting with postgres
  yum:
    name: [ python-psycopg2, libselinux-python ]
    state: present

- name: initiate postgres database
  command: '/usr/pgsql-11/bin/postgresql-11-setup initdb'
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf

- name: change ident connections to use md5
  replace:
    path: /var/lib/pgsql/11/data/pg_hba.conf
    regexp: '^(host.*)ident$'
    replace: '\1md5'

- name: start postgres and enable at boot
  service:
    name: postgresql-11
    enabled: yes
    state: started
