---
# Tasks to update an OMERO server and database

- name: backup the existing database
  become: yes
  become_user: omero
  postgresql_db:
    name: "{{ omero_db_name }}"
    state: dump
    login_host: localhost
    login_user: "{{ omero_db_user }}"
    login_password: "{{ omero_db_pass }}"
    target: "omero-{{ old_version }}.pre-{{ omero_version }}.dump.gz"

# looks like Ansible postgresql_db restore won't load a postgres dump file yet
# https://github.com/ansible/ansible-modules-core/issues/2731
#- name: update the schema to omero_version
#  become: yes
#  become_user: postgres
#  postgresql_db:
#    name: "{{ omero_db_name }}"
#    state: restore
#    target: "{{ omero_update_patch }}"
#    owner: "{{ omero_db_user }}"

- name: use shell to patch the DB to new version
  become: yes
  become_user: "{{ omero_user_name }}"
  shell: "PGPASSWORD={{ omero_db_pass }} psql -w -h localhost -U {{ omero_db_user }} {{ omero_db_name }} < {{ omero_update_patch }} > {{ omero_update_db_output }}"
  when: major_update

- name: copy config of older version
  become: yes
  become_user: "{{ omero_user_name }}"
  copy:
    src: "{{ previous_installation }}/etc/grid/config.xml"
    dest: "{{ omero_home }}/{{ omero_server_link }}/etc/grid/config.xml"
    remote_src: yes
  when: copy_config
