---
# Download and install hdf5.

- name: download the hdf5 source
  get_url: url=https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.14/src/hdf5-1.8.14.tar.gz
           dest=/usr/local/src/hdf5-1.8.14.tar.gz

- name: unpack the hdf5 source tarball
  command: tar -zxf hdf5-1.8.14.tar.gz
  args:
    chdir: /usr/local/src/
    creates: /usr/local/src/hdf5-1.8.14/README.txt

- name: configure hdf5
  command: ./configure --prefix=/usr/local --enable-fortran --enable-cxx
  args:
    chdir: /usr/local/src/hdf5-1.8.14/
    creates: /usr/local/src/hdf5-1.8.14/config.log
  register: configuring_hdf5

- name: make hdf5
  command: make
  args:
    chdir: /usr/local/src/hdf5-1.8.14/
  when: configuring_hdf5|changed

- name: install hdf5
  command: make install
  args:
    chdir: /usr/local/src/hdf5-1.8.14/
  when: configuring_hdf5|changed
