# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
export JAVA_HOME=/usr/lib/jvm/jre
export JRE_HOME=/usr/lib/jvm/jre
export ICE_HOME=/usr/share/Ice-3.6.5
export POSTGRES_HOME=/usr
export OMERO_PREFIX={{ omero_home }}/{{ omero_server_link }}
export OMERODIR=$OMERO_PREFIX
export OMERO_DATA_DIR={{ omero_data_dir }}
export PATH=$PATH:$JAVA_HOME/bin:$ICE_HOME:$POSTGRES_HOME/bin:$OMERO_PREFIX/bin
export LD_LIBRARY_PATH=/usr/share/java:/usr/lib:/usr/local/lib
source {{ omero_home }}/env/bin/activate
