---
# Ansible Playbook to install and configure an OMERO 5.4.1 server.

- name: install omero
  become: true
  become_method: sudo
  hosts: all
  vars_files:
    - vars.yml

  roles:
    - epel
    - build_tools
    - ferm
    - nginx
    - postgres
    - python
    - ice
    - omero
    - omero_web
    - db_backup

  tasks:
    - name: disable SELinux
      selinux: state=disabled
