---
# Ansible Playbook to update OMERO server.

- name: update omero
  hosts: all
  vars_files:
    - vars.yml

  roles:
    - python
    - get_omero_version
    - updatedb

  handlers:
    - name: Include ferm handlers
      include: tasks/ferm/handlers/main.yml
