---
# Ansible Playbook to update OMERO server.

- name: update omero
  hosts: all
  vars_files:
    - vars.yml

  roles:
    # - postgres
    # - ice
    - get_omero_version
    # - nginx 
    #  - updatedb
