---
# Download, install & configure ICE

- name: add the zeroc repo
  get_url:
    url: https://zeroc.com/download/Ice/3.6/el7/zeroc-ice3.6.repo
    dest: /etc/yum.repos.d/

- name: install ICE packages
  yum:
    name: [ glacier2, icebox, icegrid, icepatch2, libfreeze3.6-c++, libicestorm3.6 ]
    state: present

- name: install other packages
  yum:
    name: [ bzip2-devel, openssl-devel ]
    state: present

- name: open up the ICE port
  lineinfile:
    dest: /etc/ferm/ferm.conf
    line: 'proto tcp dport 4061 ACCEPT;'
    insertafter: '# Ansible specified rules.'
